### ISSUE TITLE
Uh oh, seems like the plugin has broken...

### ISSUE THREAD

**Issue by IchiKen98** [WhiteXZ/Localized-Chat#2]
Hi there, i have found an issue while trying your plugin. When i said something in the chat and the pop up message show up just "O" everytime. Yeah, quite annoying...

**Comment by QuiCM** [comment]
Cheers, I'll have a look and see what I can do

**Comment by QuiCM** [comment]
Hi mate, i've pushed another update that should fix this problem. Also updated for Terraria 1.4.0.3 :)

**Comment by IchiKen98** [comment]
Worked! Thanks and sorry for the reply too late ):
